# Tutorial Learn TensorFlow for Machine Learning

Tensorflow merupakan library yang banyak digunakan untuk melakukan machine learning app. Library ini banyak digunakan karena kegunaannya yang dalam melakukan pekerjaan secara pararel. Yang mana, hal tersebut sangat dibutuhkan pada proyek machine learning.

Namun, kekurangan dari tensorflow adalah kita tidak dapat sembarangan dalam melakukan import karena kebututah (requirements) yang dibutuhkan untuk menjalankan library ini dalam suatu proyek machine leraning kita harus memenuhi versi yang dibutuhkan oleh tensorflow. Jika salah satu versi library lain yang kita gunakan tidak sesuai maka tensorflow tidak dapat digunakan.

---



## Set up TensorFlow

In [ ]:
import tensorflow as tf # melakukan import tensorflow
print('tf version: ', tf.__version__) # melihat versi tensorflow yang telah terinstall

tf version:  2.17.1


In [ ]:
import numpy as np

## Insert basic operations



In [ ]:
# membuat tensor
a = tf.constant([2,3,4]) # tensor tetap
b = tf.constant([4,5,6])

# buat operasi matematika untuk menghitung inisiasi tensor
c = a + b
d = a * b

print('tensor a: ', a)
print('tensor b: ', b)
print('penjumlahan: ', c)
print('perkalian: ', d)

tensor a:  tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tensor b:  tf.Tensor([4 5 6], shape=(3,), dtype=int32)
penjumlahan:  tf.Tensor([ 6  8 10], shape=(3,), dtype=int32)
perkalian:  tf.Tensor([ 8 15 24], shape=(3,), dtype=int32)


> Dari output di atas kita bisa lihat output teridiri dari value, shape, dan dtype. Ketika menggunakan fungsi tf.constant() nilai akan bersifat tetap dan tidak dapat diubah setelah dibuat (immutable tensor). Fungsi ini hampir mirip dengan fungsi Array pada numpy. tf.constant ini digunakan untuk:
1.   Untuk menyimpan nilai tetap
2.   Untuk membuat input awal dari operasi tensor lainnya
3.   Untuk membuat tensor dummy untuk melakukan pengujian dan debugging



## Make basic model

In [ ]:
# buat data sederhana
xs = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype= np.float32)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype= np.float32)
# jika diperhatikan array di atas dapat memebentuk pola y = 2x-1

# buat model dasar menggunakan tensorflow
basic_model = tf.keras.Sequential(
    # membuat layer (disini hanya dibuat satu layer)
    # dalam layer tersebut terdapat 1 neuron yang diinisiasi sebagai units=1
    # kemudian dalam input neuron kita perlu menginput 1 nilai yaitu x pada pola y = 2x+1
    [tf.keras.layers.Dense(units=1, input_shape=[1])]
)

# eksekusi model
# kunci dalam melakukan eksekusi model terdapat 2 fungsi utama loss dan optimizer
# yang dilakukan pada code ini mesin akan menebak relasi atau hubungan dari setiap angka
# ketika mesin telah menemukan prediksi dari relasi atau pola dari setiap angka adalah y = 2x+1
# mesin akan melatih apakah prediksi tersebut bagus atau tidak menggunakan fungsi loss
# dan dengan bantuan optimizer untuk melakukan prediksi lainnya
# logika ini akan melakukan terus menerus hingga menemukan pola yang benar
basic_model.compile(optimizer='sgd', loss='mean_squared_error')

# melatih model
# pada code di bawah ini model akan dilakukan perulangan sebanyak 500 kali setiap kali melakukan prediksi pola
basic_model.fit(xs, ys, epochs=500, verbose=0)

# output
# disini kita akan melakuan memasukkan nilai x=10 pada pola yang telah diprediksi
# maka y = 2(10)-1 = 19
print('hasil prediksi: ', basic_model.predict(np.array([10.0], dtype=np.float32)))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
hasil prediksi:  [[18.984713]]


In [ ]:
# load data sederhana
x_train = np.array([1, 2, 3, 4], dtype= np.float32)
y_train = np.array([2, 3, 5, 7], dtype= np.float32)

# membuat model linear sederhana y = wx + b
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 1, input_shape=[1]) # unit = jumlah neuron
])

# kompilasi model
model.compile(optimizer='sgd', loss='mean_squared_error')

# latih model
model.fit(x_train, y_train, epochs=200, verbose=0)

# prediksi model
# print('model untuk x=5 : ' , model.predict([5])) # output ini tidak dapat dilakukan karena struktur output [5] tidak dapat dikenali sehingga harus dilakukan konversi
# print('model untuk x=5 : ' , model.predict(np.array([5], dtype=np.float32))) # prediksi ini menggunakan np.array
print('model untuk x=5 : ' , model.predict(tf.constant([5], dtype=tf.float32))) # prediksi ini menggunakan tensor

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
model untuk x=5 :  [[8.214091]]


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4 (20.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

> Fungsi tf.keras.Sequential pada kode di atas merupakan implemnetasi dari neural network. Neural Network (NN) merupakan metode komputasi yang terinspirasi dari cara kerja sistem saraf manusia neuron. Dalam komputasi neural network terbagi dalam beberapa layer layaknya neuron pada manusia. Pada neuron input dari neuron kecil lain akan mengirimkan sinyal ke neuron inti dan disalurkan ke saraf lain.

> Dalam NN sinyal/input yang dikirim diberikan bobot. Sehingga dalam komputasi NN biasanya terdapat layer, secara umum terdapat input layer, hidden layer, dan output layer. Input layer merupakan lapisan pertama yang mengirimkan input eksternal, jumlah input layer sama dengan jumlah feature yang ada pada data input. Sebagai contoh jika kita melakukan input gambar dengan ukuran 28x28, maka jumlah input layer terdiri dari (28x28) 784 neuron. Hidden layer, merupakan layer tempat pemrosesan terjadi yang letaknya di antara input layer dan output layer, cara kerja layer ini melakukan representasi input menjadi lebih abstrak. Namun, jumlah hidden layer begantung dari kompleksitas masalah yang ingin dipecahkan. Output layer merupakan layer output dari setiap representasi hidden layer, sebagi contoh jika represntasi yang dihasiklan adalah kategori dari 10 gambar maka output layer akan tediri dari 10 neuron.



## Classification with dummy data

In [ ]:
# Klasifikasi menggunakan neural network
# Dataset dummy (OR gate)
j_train = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
z_train = np.array([[0], [1], [1], [1]], dtype=np.float32)

# membuat model untuk klasifikasi
# aktivasi model terdapat sigmoid, relu, tanh
klaf_model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=4, activation='relu', input_shape=[2]),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

# kompilasi model
klaf_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# latih model
klaf_model.fit(j_train, z_train, epochs= 100, verbose=0)

# prediksi model
print('prediksi :')
print(klaf_model.predict(j_train))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


prediksi :
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[[0.5340164 ]
 [0.6199702 ]
 [0.39649487]
 [0.4971674 ]]


In [ ]:
klaf_model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 4)                   │              12 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │               5 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 53 (216.00 B)

 Trainable params: 17 (68.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 36 (148.00 B)

> Pada kode di atas atribut activation berfungsi untuk memilih model apa yang ingin digunakan dalam menghitung output dari neuron berdasarkan input yang diterima. Biasnya hasil dari aktivasi tidak bersifat linear, sehingga terkadang diperlukan model untuk menghitung model yang lebih kompleks

> Terdapat beberap jenis fungsi aktivasi yang digunakan:
1.   Sigmoid: memiliki rentan nilai dari 0 hingga 1.
2.   ReLU: memiliki nilai output positif sesuai dengan positif yaitu 1, sebaliknya jika negatif maka 0.
3.   Tanh: memiliki rentan nilai -1 hingga 1.

> Biasanya sigmoid digunakan dalam klasifikasi biner. ReLU (restricted linear unit), fungsi ini biasa digunakan untuk masalah regresi dan klasifikasi. Tanh, fungsi ini biasa digunakan pada hidden layer untuk menghasilkan represntasi yang simeteris terhadap nilai 0.

>